version: '3.8'

services:
  ms-customer-data-management:
    image: ms-customer-data-management-image
    container_name: ms-customer-data-management
    ports:
      - "8899:8899"  # Expondo a porta 8899 do seu microserviço para o host
    depends_on:
      - sysmap-service
    networks:
      - backend

  sysmap-service:
    image: sysmap/service-image
    container_name: sysmap-service
    expose:
      - "7001"  # Expondo apenas internamente no Docker (não mapeado para o host)
    networks:
      - backend

networks:
  backend:
    driver: bridge
