spring:
    application:
        name: ms-customer-data-management

    webservice:
        wsSysmap:
            #se não estiver utilizando docker e quiser rodar localmente precisa utilizar a primeira opção
            #uri: http://localhost:7001/demo/ws
            uri: http://host.docker.internal:7001/demo/ws
            class:
                package: br.com.sysmap.dip.infrastructure.soap.wsSysmap.stub


server:
    port: 8899
