spring:
    application:
        name: ms-customer-data-management

    webservice:
        wsSysmap:
            uri: http://127.0.0.1:7001/demo/ws
            class:
                package: br.com.sysmap.dip.infrastructure.soap.wsSysmap.stub


server:
    port: 8899
